#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Uso: ./moodle nombre_corto \"Nombre largo\" <url.edocere.com>"
    exit 1
fi

echo "Nombre corto:$1"
echo "Nombre largo:$2"

if [ "$#" -eq 3 ]; then
	echo "URL: $3"
else
	echo "No usaremos URL"
fi

exit 0
echo "Creando directorio y copiando base"
cd /moodle/mt/
cp -rf ../moodle3.4.2 $1
echo "Modificando archivo config.php"
if [ "$#" -eq 3 ]; then
	cp /moodle/mt/$1/config-site.php /moodle/mt/$1/config.php
	sed -i -- 's/site/'"$1"'/g' /moodle/mt/$1/config.php
	sed -i -- 's/urlmoodle/'"$3"'/g' /moodle/mt/$1/config.php
else
	sed -i -- 's/site/'"$1"'/g' /moodle/mt/$1/config.php
fi
echo "Creando BBDD y usuario BBDD"
mysql -u root --password=D0cendus.P0 -e "CREATE DATABASE IF NOT EXISTS $1 DEFAULT CHARACTER SET=utf8mb4 COLLATE 'utf8mb4_unicode_ci'"
mysql -u root --password=D0cendus.P0 -e "grant all privileges on $1.* to $1@'%' identified by 'pepito.P0'"
mysql -u root --password=D0cendus.P0 -e "flush privileges"
echo "Creando directorio de datos (moodledata)"
mkdir -p /moodle/data/$1
chown www-data:www-data /moodle/data/$1
echo "Creando sitio en nginx"
if [ "$#" -eq 3 ]; then
	cp /moodle/nginx/site-url /etc/nginx/sites-available/$1
	sed -i -- 's/site/'"$1"'/g' /etc/nginx/sites-available/$1
	sed -i -- 's/urlmoodle/'"$3"'/g' /etc/nginx/sites-available/$1
else
	cp /moodle/nginx/site /etc/nginx/sites-available/$1
	sed -i -- 's/site/'"$1"'/g' /etc/nginx/sites-available/$1
fi
ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/
systemctl restart nginx
echo "Instalando Moodle"
cd /moodle/mt/$1/admin/cli/
sudo -u www-data /usr/bin/php install_database.php --lang=es --adminpass=D0cendus.P0 --agree-license --fullname="$2" --shortname=$1 --adminemail=soporte@edocere.com
echo "Creando configuraciones básicas"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config set value = 'tls' where name = 'smtpsecure';"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config set value = 'email-smtp.us-east-1.amazonaws.com' where name = 'smtphosts';"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config set value = 'AKIAINACNIOFNS32HETQ' where name = 'smtpuser';"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config set value = 'Ar/0WTH1a0m+VzO0a8QDoYPSFA411U+Aw3K0DokcIB68' where name = 'smtppass';"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config set value = '0' where name = 'autolang';"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config set value = '0' where name = 'langmenu';"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config set value = 'es_CL.utf8' where name = 'locale';"
mysql -u root --password=D0cendus.P0 -e "update $1.mdl_config_plugins set value = '.helplink, .sitelink {display:none;}' where name = 'customcss' and plugin = 'theme_clean';"
exit 0
